### ISSUE TITLE
[BUG] OneSDK overrides the custom `accept` header

### ISSUE THREAD

**Issue by jnv** [superfaceai/one-sdk-js#264] opened 2022-07-26 11:05 UTC
Given the following http request:

```hcl
  http GET "/example" {
    request {
      headers {
        Accept = "application/json"
      }
    }
    response 200 "application/json" {
      // handle correct result
    }
    response {
      // handle everything else
    }
  }

```

## Expected Behavior

The request should be sent with `accept: application/json`.

## Current Behavior

I see the following with `DEBUG=superface:http:sensitive` env:

![](https://user-images.githubusercontent.com/616767/180990386-73b76cf0-203f-4bb4-8c6b-08a4d8bc5aa2.png)

In case I name the header in the map as `accept` (lowercase a), I don't see it in the debug output at all.

## Possible Solution

Note that this _could_ be an issue with debug output, I didn't test what header actually reaches the endpoint in the end.

The current implementation of the interpreter [collects expected response types](https://github.com/superfaceai/one-sdk-js/blob/0bbb6f74b328294a98041a50e756659666ae26b4/src/core/interpreter/map-interpreter.ts#L328-L337) and passes them to the request. If any of the response handlers is missing a response type, `*/*` is set instead. It is likely that somewhere down the line, the passed-in `accept` parameter overrides the user-provider header.

## Your Environment

* Version used `@superfaceai/one-sdk` `1.5.0`
* Environment name and version `v16.15.0`
* Link to your project https://github.com/superfaceai/station

**Comment by freaz** [comment] 2022-10-04 14:50
Finally got to this and definitely something odd is happening there.

<img width="1873" alt="image" src="https://user-images.githubusercontent.com/959390/193851531-84fb960f-2174-4d88-8c91-0ee2b096dde9.png">

And it seems it is caused by case sensitivity when resolving headers.

<img width="1919" alt="image" src="https://user-images.githubusercontent.com/959390/193851893-aa9ce43e-841f-479d-aa69-ef1519d6ebd5.png">

**Closed** 2022-10-10 08:30 UTC
Labels: bug
